### PR TITLE
Fix/apply at start

### LINKED ISSUE #491: Pose-core: flip & applyAtStart clash
## Describe the bug
It's impossible to make an entering flip animation for posed elements hidden with `applyAtEnd`, because of those lines:

https://github.com/Popmotion/popmotion/blob/5df3b13e8e7a32e8d502a9f1dff1454e01469a21/packages/pose-core/src/factories/setter.ts#L210-L231

`transformPose` call first calculates the flip by calling `explicitlyFlipPose` and only later `applyAtStart` gets applied. The intuition would tell me that this should work and that `applyAtStart` should play nicely with flip here, OTOH `applyAtEnd` & `applyAtStart` ideally would behave the same and assuming my intuition is correct here for `applyAtStart` then fixing this would create an opposite problem of not being able to hide the element with flip.

So maybe it's just matter of documenting this behaviour?

## How to reproduce
```js
const Box = posed.div({
	visible: {
		width: '20vw',
		height: '40vh',
		flip: true,
		applyAtStart: {
			display: 'block',
		},
	},
	hidden: {
		width: '1px',
		height: '1px',
		flip: true,
		applyAtEnd: {
			display: 'none',
		},
	},
})
```

### PR DESCRIPTION
**Pull request by Andarist**
Fixes #491 & possibly #698 too.

### CODE REVIEW

File: packages/pose-core/src/factories/setter.ts [hunk 1]
```diff
@@ -227,8 +217,16 @@ const createPoseSetter = <V, A, C, P>(
           setValue,
           setValueNative
         );
+        baseTransitionProps.elementStyler.render();
```
Comment (Andarist) [inline packages/pose-core/src/factories/setter.ts]: this is needed because otherwise those 2:
https://github.com/Popmotion/popmotion/blob/916df7350307d3127bb2dbdd9ea721e03888791c/packages/popmotion-pose/src/dom/unit-conversion.ts#L55
https://github.com/Popmotion/popmotion/blob/916df7350307d3127bb2dbdd9ea721e03888791c/packages/popmotion-pose/src/dom/unit-conversion.ts#L81
would return outdated computed styles.

Most likely the same happens in flip.ts

Comment (Andarist) [reply packages/pose-core/src/factories/setter.ts]: Hm, seems like elementStyler is DOM-specific - so this call has to be moved out of `pose-core`.

How would you suggest doing this?

Comment (InventingWithMonster) [reply packages/pose-core/src/factories/setter.ts]: Ugh. Yeah this makes sense. 

FLIP was a mistake.

You can add "slots" to `pose-core`, that pose flavours can hook into. The same way there's

```
if (transformPose) nextPose = transformPose(nextPose, next, state);
```

You could add an optional function to the `pose-core` factory that's something like "forceRender", kinda generic, that in `popmotion-pose` is configured to be `props.elementStyler.render()` and you call it if you've set `applyAtStart`

Comment (Andarist) [reply packages/pose-core/src/factories/setter.ts]: Cool, was thinking about such hook myself, couldnt settle on a name - `forceRender` sounds nice 👌 

> FLIP was a mistake.

Why? :p do you mean using this technique or its current implementation?

Comment (Andarist) [reply packages/pose-core/src/factories/setter.ts]: Also - the quirk of this solution is that `applyAtStart` cant be transformed (while ie `applyAtEnd` actually is transformed in some cases). It is how it is though, cant figure out any legit use case for transforming `applyAtStart` anyway.

**Comment by Andarist** [comment]
@InventingWithMonster added optional `forceRender` to poseFactory, should be ready to be merged in

**Comment by Andarist** [comment]
This also fixes #644 . That demo still doesnt look too nice though, because of this https://github.com/Popmotion/popmotion/pull/564#issuecomment-430957541

File: packages/pose-core/src/factories/setter.ts (hunk 1 above)
Comment (InventingWithMonster) [reply packages/pose-core/src/factories/setter.ts]: Mostly because I think 80% of all the bugs we've seen in Pose have been around FLIP!

**Comment by InventingWithMonster** [comment]
Awesome thanks
